title: Project Post
create_title: New Project Post
taxonomies: false
fields:
  website:
    type: text
    display: Website
    instructions: What is the URL for this project?
    width: 50
    validate: URL
  hero_image:
    type: assets
    display: Hero Image
    instructions: Main image thumbnail on Projects page
    container: main
    folder: /
    width: 50
    restrict: false
  description:
    type: markdown
    display: Project Description
    instructions: What did you do on this project?
    cheatsheet: true
    container: main
    folder: projects
    validate: required
    restrict_assets: false
  images:
    type: assets
    display: Images of the project
    instructions: 'Images cropped to **1280 x 775 @ 72 DPI**'
    container: main
    folder: /
    restrict: false
